--MARCA CARRO
INSERT INTO FABRICANTE(ID,NOME) VALUES(1,'CHEVROLET');
INSERT INTO FABRICANTE(ID,NOME) VALUES(2,'VOLKSWAGEN');
INSERT INTO FABRICANTE(ID,NOME) VALUES(3,'FIAT');
INSERT INTO FABRICANTE(ID,NOME) VALUES(4,'MERCEDES-BENZ');
INSERT INTO FABRICANTE(ID,NOME) VALUES(5,'CITROEN');
INSERT INTO FABRICANTE(ID,NOME) VALUES(22,'PEUGEOT');
INSERT INTO FABRICANTE(ID,NOME) VALUES(23,'TOYOTA');
INSERT INTO FABRICANTE(ID,NOME) VALUES(24,'RENAULT');
INSERT INTO FABRICANTE(ID,NOME) VALUES(13,'FORD');
INSERT INTO FABRICANTE(ID,NOME) VALUES(14,'HYUNDAI');
INSERT INTO FABRICANTE(ID,NOME) VALUES(15,'JAC');
INSERT INTO FABRICANTE(ID,NOME) VALUES(16,'KIA');
INSERT INTO FABRICANTE(ID,NOME) VALUES(261,'OUTROS');
INSERT INTO FABRICANTE(ID,NOME) VALUES(7,'HONDA');
INSERT INTO FABRICANTE(ID,NOME) VALUES(32,'AUDI');
INSERT INTO FABRICANTE(ID,NOME) VALUES(53,'VOLVO');
INSERT INTO FABRICANTE(ID,NOME) VALUES(86,'JAGUAR');
INSERT INTO FABRICANTE(ID,NOME) VALUES(87,'JEEP');
INSERT INTO FABRICANTE(ID,NOME) VALUES(96,'LAND ROVER');

--MODELO CARRO

INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(190,'PALIO',3,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(193,'PUNTO',3,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(194,'SIENA',3,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(195,'STILO',3,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(196,'STRADA',3,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(199,'UNO',3,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(827,'SANDERO STEPWAY',24,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(1388,'NEW FIESTA',13,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(1397,'JEEP',87,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(1971,'ETIOS',23,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(1972,'ONIX',1,'C');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES(1973,'HB20',14,'C');


-- -- --MARCA MOTO
INSERT INTO FABRICANTE(ID,NOME) VALUES(1,'TRIUMPH');
INSERT INTO FABRICANTE(ID,NOME) VALUES(7,'HONDA');
INSERT INTO FABRICANTE(ID,NOME) VALUES(36,'BMW');
INSERT INTO FABRICANTE(ID,NOME) VALUES(59,'SUZUKI');
INSERT INTO FABRICANTE(ID,NOME) VALUES(135,'YAMAHA');
INSERT INTO FABRICANTE(ID,NOME) VALUES(170,'KAWASAKI');
INSERT INTO FABRICANTE(ID,NOME) VALUES(204,'HARLEY-DAVIDSON');
INSERT INTO FABRICANTE(ID,NOME) VALUES(197,'DUCATI');
-- -- 
-- -- --MODELO MOTO
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('754','BIZ',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('761','CB 300R',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('763','CB 400',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('764','CB 500',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('765','CB 600 HORNET',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('766','CBR 1000F',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('767','FIREBLADE CBR',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('768','CBR 450',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('769','CBR 600',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('771','TWISTER CBX 250',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('772','CBX 750F',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('773','CG FAN',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('774','CG TITAN',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2965','CRF 230/250',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2966','CRF 450',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2968','NX 650 DOMINATOR',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2969','CR 250',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2970','CR 125',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2417','CB 50',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2419','BOLDOR CB 900',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2420','CBF 600',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2421','CBR 400RR',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2423','CBX 1000',7,'M');