-- -- --MARCA MOTO
INSERT INTO FABRICANTE(ID,NOME) VALUES(1,'TRIUMPH');
INSERT INTO FABRICANTE(ID,NOME) VALUES(7,'HONDA');
INSERT INTO FABRICANTE(ID,NOME) VALUES(36,'BMW');
INSERT INTO FABRICANTE(ID,NOME) VALUES(59,'SUZUKI');
INSERT INTO FABRICANTE(ID,NOME) VALUES(135,'YAMAHA');
INSERT INTO FABRICANTE(ID,NOME) VALUES(170,'KAWASAKI');
INSERT INTO FABRICANTE(ID,NOME) VALUES(204,'HARLEY-DAVIDSON');
INSERT INTO FABRICANTE(ID,NOME) VALUES(197,'DUCATI');
-- -- 
-- -- --MODELO MOTO
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('754','BIZ',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('761','CB 300R',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('763','CB 400',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('764','CB 500',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('765','CB 600 HORNET',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('766','CBR 1000F',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('767','FIREBLADE CBR',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('768','CBR 450',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('769','CBR 600',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('771','TWISTER CBX 250',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('772','CBX 750F',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('773','CG FAN',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('774','CG TITAN',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2965','CRF 230/250',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2966','CRF 450',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2968','NX 650 DOMINATOR',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2969','CR 250',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2970','CR 125',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2417','CB 50',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2419','BOLDOR CB 900',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2420','CBF 600',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2421','CBR 400RR',7,'M');
INSERT INTO AUTOMOVEL(ID,NOME,FABRICANTE_ID,TIPO_AUTOMOVEL) VALUES('2423','CBX 1000',7,'M');